export const sliderPreview =  [
    {id: 1, img: '/prev/1.jpg'},
    {id: 2, img: '/prev/2.jpg'},
    {id: 3, img: '/prev/3.jpg'},
    {id: 4, img: '/prev/4.jpg'},
    {id: 5, img: '/prev/5.jpg'},
    {id: 6, img: '/prev/6.jpg'},
    {id: 7, img: '/prev/7.jpg'},
    {id: 8, img: '/prev/8.jpg'},
    {id: 9, img: '/prev/9.jpg'},
    {id: 10, img: '/prev/10.jpg'},
    {id: 11, img: '/prev/11.jpg'},
    {id: 12, img: '/prev/12.jpg'},
    {id: 13, img: '/prev/13.jpg'},
    {id: 14, img: '/prev/14.jpg'},
    {id: 15, img: '/prev/15.jpg'},
    {id: 16, img: '/prev/16.jpg'},
    {id: 17, img: '/prev/17.jpg'},
    {id: 18, img: '/prev/18.jpg'},
]